name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  link-check:
    name: Link Check (Lychee)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          # Accept 2xx by default, plus 403/429 for sites that rate-limit/bounce CI
          # Exclude data: URIs to avoid unsupported scheme noise
          args: >-
            --verbose --no-progress
            --accept 200..=299,403,429
            --exclude "data:*"
            --timeout 20 --max-concurrency 5
            './**/*.html' './README.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  html-lint:
    name: HTML Lint (HTMLHint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Lint HTML (all *.html)
        run: npx --yes htmlhint --config .htmlhintrc "**/*.html"
